// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/BentoDashboard.tsx": () => import("../components/mockups/dashboard/BentoDashboard.tsx"),
  "./components/mockups/dashboard/PastelBentoDashboard.tsx": () => import("../components/mockups/dashboard/PastelBentoDashboard.tsx"),
  "./components/mockups/dashboard/SoftTypographyDashboard.tsx": () => import("../components/mockups/dashboard/SoftTypographyDashboard.tsx"),
  "./components/mockups/dashboard/TypographyDashboard.tsx": () => import("../components/mockups/dashboard/TypographyDashboard.tsx")
};
